export const Users = [
    {
        id:1,
        profilePicture: "assests/person/1.jpeg",
        username: "Datta Pandharmise",

    },
    {
        id:2,
        profilePicture: "assests/person/2.jpeg",
        username:"Datta Pandharmise",

    },
    {
        id:3,
        profilePicture: "assests/person/3.jpeg",
        username:"Datta Pandharmise",

    },
    {
        id:4,
        profilePicture: "assests/person/4.jpeg",
        username:"Datta Pandharmise",

    },
    {
        id:5,
        profilePicture: "assests/person/5.jpeg",
        username:"Datta Pandharmise",

    },
    {
        id:6,
        profilePicture: "assests/person/6.jpeg",
        username:"Datta Pandharmise",

    },
    {
        id:7,
        profilePicture: "assests/person/7.jpeg",
        username:"Datta Pandharmise",

    },
    {
        id:8,
        profilePicture: "assests/person/8.jpeg",
        username:"Datta Pandharmise",

    },
    {
        id:9,
        profilePicture: "assests/person/9.jpeg",
        username:"Datta Pandharmise",

    },
    {
        id:10,
        profilePicture: "assests/person/10.jpeg",
        username:"Datta Pandharmise",

    },
];

export const Posts = [
  {  id:1,
    desc : "Love for All ,Mattered for None",
    photo : "assests/person/1.jpeg",
    date: "5 mins ago",
    userId : 1,
    like : 50,
    comment : 29, },
    {  id:2,
        desc : "Love for All ,Mattered for None",
        photo : "assests/person/2.jpeg",
        date: "5 mins ago",
        userId : 2,
        like : 50,
        comment : 29,},
        {   id:3,
            desc : "Love for All ,Mattered for None",
            photo : "assests/person/3.jpeg",
            date: "5 mins ago",
            userId : 3,
            like : 50,
            comment : 29, },
            {   id:4,
                desc : "Love for All ,Mattered for None",
                photo : "assests/person/4.jpeg",
                date: "5 mins ago",
                userId : 4,
                like : 50,
                comment : 29, },
                {   id:5,
                    desc : "Love for All ,Mattered for None",
                    photo : "assests/person/5.jpeg",
                    date: "5 mins ago",
                    userId : 5,
                    like : 50,
                    comment : 29,},
                    {   id:6,
                        desc : "Love for All ,Mattered for None",
                        photo : "assests/person/6.jpeg",
                        date: "5 mins ago",
                        userId : 6,
                        like : 50,
                        comment : 29, },
                        {   id:7,
                            desc : "Love for All ,Mattered for None",
                            photo : "assests/person/7.jpeg",
                            date: "5 mins ago",
                            userId : 7,
                            like : 50,
                            comment : 29, },
                            {  id:8,
                                desc : "Love for All ,Mattered for None",
                                photo : "assests/person/8.jpeg",
                                date: "5 mins ago",
                                userId : 8,
                                like : 50,
                                comment : 29,},
                                {   id:9,
                                    desc : "Love for All ,Mattered for None",
                                    photo : "assests/person/9.jpeg",
                                    date: "5 mins ago",
                                    userId : 9,
                                    like : 50,
                                    comment : 29, },
                                    {  id:10,
                                        desc : "Love for All ,Mattered for None",
                                        photo : "assests/person/10.jpeg",
                                        date: "5 mins ago",
                                        userId : 10,
                                        like : 50,
                                        comment : 29, }
                                    ];